### ISSUE TITLE
Delay with office hours - Jan 13th

### ISSUE THREAD

**Issue by mtello22** [STAT540-UBC-2022/Discussion#3]
Hello everyone,
I'm having technical difficulties, I will need to move the office hours to 11:40 AM.
If this change prevents you from attending, please feel free to email me so we can work on your problem.
I'm sorry for the short notice.
Best,

**Comment by ashleighthomas** [comment]
Hi Marco! I'm not seeing any zoom links or any information for office hours for TAs, I only see it for the instructors. Where is this information posted? Thank you!

**Comment by mtello22** [comment]
You're right. I just added the link to canvas. Please let me know if it doesn't work.
